server:
  port: 8003

# mybatis配置
mybatis:
  type-aliases-package: com.cfz.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

# mp配置
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启SQL语句打印

# spring配置
spring:
  application:
    name: springcloud-provider-dept
  dataSource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud03?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root

#Eureka的配置，注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://localhost1:7001/eureka/,http://localhost2:7002/eureka/,http://localhost3:7003/eureka/
  instance:
    prefer-ip-address: true
    instance-id: springcloud-provider-dept-8003   #修改erueka上的默认描述信息

# info配置
info:
  app.name: chenfengzhen-springcloud
  company.name: blog-chenfengzhen